
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Jason Yang (양기창)  ## put your name
title: 'Android &amp; DeepLearning Engineer'  ## your title
location: Seoul, KR


## Social Profiles
facebook: http://www.facebook.com/DEVkichang  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
